version: '3'
services:
  poker-api:
    container_name: poker-api
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./poker/presentations/poker-api/Dockerfile
    tty: true
    volumes:
      - ./poker/presentations/poker-api:/app/poker/presentations/poker-api/
      - ./poker/presentations/poker-api/node_modules:/app/poker/presentations/poker-api/node_modules/
    command: bash -c "npm run start"
    ports:
      - 3000
